London Subway Python & Java Functions
fivetran/functions pull request #18
Opened 2021-05-11 19:13 UTC by fivetran-monilbansal

2021-05-18 05:39 UTC, fivetran-shashanktripathi requested changes
Python version looks good. Java version needs some changes as we had discussed.

2021-05-18 10:38 UTC, fivetran-shashanktripathi requested changes
Some indentation changes as discussed

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +    public Record(Object since, Map<String, List<Map<String, Object> > > insert, Map<String, Map<String, List<String> > > schema, Map<String, Object> state ) {
Take `hasMore` as param here.

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +      Record record = new Record(since, insert, schema, state);
```suggestion
      Record record = new Record(since, insert, schema, state, true);
```
After you've added the hasMore there

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
Can remove objectMapper

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +  Record apiResponse() {
private

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +        Map<String,Object> tempMap = new HashMap<>();
linesDetailMap

2021-05-18 10:38 UTC, fivetran-shashanktripathi commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +      //Getting the response code
can remove this

2021-05-19 09:24 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
Done

2021-05-19 09:24 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +  Record apiResponse() {
Done

2021-05-19 09:25 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +      Record record = new Record(since, insert, schema, state);
DoneDone

2021-05-19 09:25 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +    public Record(Object since, Map<String, List<Map<String, Object> > > insert, Map<String, Map<String, List<String> > > schema, Map<String, Object> state ) {
Done

2021-05-19 09:27 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +        Map<String,Object> tempMap = new HashMap<>();
Done

2021-05-19 09:29 UTC, fivetran-monilbansal commented on LondonSubway/Java/src/main/java/com/example/Example.java
> +      //Getting the response code
Done

2021-05-19 09:41 UTC, fivetran-shashanktripathi approved these changes
Approving after the changes we discussed are done.

2021-05-20 11:03 UTC, merged